version: '3'

services:
  frontend:
    build: ./frontend-react
    ports:
      - "8080:8080"
    environment:
      - VITE_PRODUCT_API=http://product-service:5000
      - VITE_CART_API=http://cart-service:5001
      - VITE_CHECKOUT_API=http://checkout-service:5002
      - VITE_ORDER_API=http://order-service:5003
    depends_on:
      - product-service
      - cart-service
      - checkout-service
      - order-service

  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/products

  cart-service:
    build: ./cart-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379

  checkout-service:
    build: ./checkout-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - ORDER_API=http://order-service:5003
      - CART_API=http://cart-service:5001

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URI=mongodb://mongo:27017/orders

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: