version: "3.8"

services:
  product-service:
    build:
      context: ./backend/product-service
    container_name: product-service
    ports:
      - "5101:5000"
    restart: unless-stopped

  cart-service:
    build:
      context: ./backend/cart-service
    container_name: cart-service
    ports:
      - "5102:5000"
    restart: unless-stopped

  checkout-service:
    build:
      context: ./backend/checkout-service
    container_name: checkout-service
    ports:
      - "5103:5000"
    depends_on:
      - order-service
    restart: unless-stopped

  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    ports:
      - "5104:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-react
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_PRODUCT_API=http://localhost:5101
      - VITE_CART_API=http://localhost:5102
      - VITE_CHECKOUT_API=http://localhost:5103
      - VITE_ORDER_API=http://localhost:5104

    volumes:
      - ./frontend-react/src:/app/src
      - ./frontend-react/public:/app/public
      - ./frontend-react/index.html:/app/index.html
    # add any other source code files or folders explicitly

    working_dir: /app
    command: npm run dev
    depends_on:
      - product-service
      - cart-service
      - checkout-service
      - order-service
    restart: unless-stopped
