version: "3.8"

services:
  product-service:
    build:
      context: ./backend/product-service
    ports:
      - "5101:5000" # host 5101 to container 5000
    container_name: product-service

  cart-service:
    build:
      context: ./backend/cart-service
    ports:
      - "5102:5000" # host 5102 to container 5000
    container_name: cart-service

  checkout-service:
    build:
      context: ./backend/checkout-service
    ports:
      - "5103:5000" # host 5103 to container 5000
    container_name: checkout-service

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "5173:5173"
    container_name: frontend
    environment:
      - VITE_PRODUCT_API=http://localhost:5101
      - VITE_CART_API=http://localhost:5102
      - VITE_CHECKOUT_API=http://localhost:5103
    volumes:
      - ./frontend-react:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - product-service
      - cart-service
      - checkout-service
