name: Test Branch Workflow

on:
  push:
    branches: [test-workflows]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "This is a test from the test-workflows branch"